### ISSUE TITLE
How to include, require or load external file?

### ISSUE THREAD

**Issue by gamecubate** [burtonsamograd/ps2js#4]
For the sake of refactoring, I want to save some functionality in a separate file. How do I include/require/load that file at compile time?

**Comment by gamecubate** [comment]
I am also asking the Parenscript maintainer in case this is more relevant to him than to you.

**Comment by burtonsamograd** [comment]
In Sigil, you can include code at compile time  using (load "filename.ps").

**Comment by gamecubate** [comment]
Thanks. Works very nicely. Was this documented anywhere? I may have missed it.
